### ISSUE TITLE
 Trying to copy from a source that does not exist

### ISSUE THREAD

**Issue by darekf77** [LeoColomb/generator-latex#24]
**Platform : windows**

I got error in terminal:

```
? Do you need a glossary? Yes
? Do you need to generate .pdf figures from .svg automatically? No

events.js:160
      throw er; // Unhandled 'error' event
      ^
 AssertionError: Trying to copy from a source that does not exist: C:\Users\...\master_thesis\node_modules\generator-latex\generators\app\templates\src\gloss
.tex
    at EditionInterface.exports.copy (C:\Users\...\master_thesis\node_modules\mem-fs-editor\lib\actions\copy.js:47:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\...\master_thesis\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:10:8)
    at writing (C:\Users\...\master_thesis\node_modules\generator-latex\generators\app\index.js:143:15)
    at Object.<anonymous> (C:\Users\...\master_thesis\node_modules\yeoman-generator\lib\index.js:408:23)
    at C:\Users\...\master_thesis\node_modules\run-async\index.js:25:25
    at C:\Users\...\master_thesis\node_modules\run-async\index.js:24:19
    at C:\Users\...\master_thesis\node_modules\yeoman-generator\lib\index.js:409:9
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
 PS C:\Users\...\master_thesis>
```

**Comment by LeoColomb** [comment]
Thanks a lot for filing this issue!
We'll triage and take a look at it as soon as possible! :eyes:

**Comment by LeoColomb** [comment]
It should be fixed. Upgrade your local version and retry.

Thanks again for the issue! 💌
